# Generated by Django 6.0.5 on 2026-05-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
