# Generated by Django 6.0.5 on 2026-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
