# Generated by Django 6.0.5 on 2026-06-16 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_is_free_course_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='resource_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Thumbnail'),
        ),
    ]
