# Generated by Django 6.0.5 on 2026-08-12 14:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_resource_file_alter_course_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(blank=True, max_length=255, verbose_name='Rol o curso realizado')),
                ('texto', models.TextField(verbose_name='Testimonio')),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
