# Generated by Django 6.0.5 on 2026-08-26 01:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Archivo de la clase'),
        ),
    ]
