"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
import cloudinary

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-local-dev-key'
)

DEBUG = os.getenv(
    'DEBUG',
    'True'
) == 'True'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'courses',
    'dashboard',
    'panel',
    'payments',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'



STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

JAZZMIN_SETTINGS = {

    "site_title": "NeuroEducación Admin",

    "site_header": "NeuroEducación",

    "site_brand": "NeuroEducación",

    "site_logo": None,

    "welcome_sign": "Panel administrativo",

    "copyright": "Impulsa Studio Digital",

    "search_model": ["courses.Course"],

    "topmenu_links": [

        {
            "name": "Inicio",
            "url": "/",
            "permissions": ["auth.view_user"]
        },

        {
            "model": "courses.Course"
        },

    ],

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "order_with_respect_to": [

        "courses",
        "auth",
    ],

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "courses.Course": "fas fa-graduation-cap",

        "courses.Module": "fas fa-layer-group",

        "courses.Lesson": "fas fa-play-circle",

    },

    "default_icon_parents": "fas fa-chevron-circle-right",

    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,

    "custom_css": "css/admin.css",

}

MERCADO_PAGO_ACCESS_TOKEN = os.getenv(
    'MERCADO_PAGO_ACCESS_TOKEN'
)

RESEND_API_KEY = os.getenv(
    'RESEND_API_KEY'
)

ADMIN_NOTIFICATIONS_EMAIL = os.getenv(
    'ADMIN_NOTIFICATIONS_EMAIL'
)

# Lista separada por comas en la env var CSRF_TRUSTED_ORIGINS,
# por ejemplo: "https://neuroeducacion.onrender.com,https://miapp.com"
# Así no queda pisado a un dominio fijo cada vez que cambia de
# hosting (Railway -> Render -> lo que sea).
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]



cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'accounts.email_backend.ResendEmailBackend'

# No se usa DEBUG para esto: en este proyecto el .env local
# trae DEBUG=False, y si atáramos el redirect a HTTPS a ese
# valor, correr el server en local (sin TLS) entraría en un
# loop de redirects. En cambio, se detecta automáticamente si
# se está corriendo en un hosting real (Railway o Render ponen
# sus propias env vars), o se puede forzar a mano con
# IS_PRODUCTION=True para cualquier otro proveedor.
RUNNING_IN_PRODUCTION = (
    os.getenv('IS_PRODUCTION') == 'True'
    or bool(os.getenv('RAILWAY_ENVIRONMENT_NAME'))
    or bool(os.getenv('RENDER'))
)

# Endurecimiento para producción. Railway y Render terminan el
# TLS y reenvían por HTTP interno con el header
# X-Forwarded-Proto, por eso hace falta SECURE_PROXY_SSL_HEADER
# para que Django sepa que la conexión original ya venía por
# HTTPS.
if RUNNING_IN_PRODUCTION:

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True