"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-local-dev-key'
)

DEBUG = os.getenv(
    'DEBUG',
    'True'
) == 'True'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'courses',
    'dashboard',
    'payments',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

JAZZMIN_SETTINGS = {

    "site_title": "NeuroEducación Admin",

    "site_header": "NeuroEducación",

    "site_brand": "NeuroEducación",

    "site_logo": None,

    "welcome_sign": "Panel administrativo",

    "copyright": "Impulsa Studio Digital",

    "search_model": ["courses.Course"],

    "topmenu_links": [

        {
            "name": "Inicio",
            "url": "/",
            "permissions": ["auth.view_user"]
        },

        {
            "model": "courses.Course"
        },

    ],

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "order_with_respect_to": [

        "courses",
        "auth",
    ],

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "courses.Course": "fas fa-graduation-cap",

        "courses.Module": "fas fa-layer-group",

        "courses.Lesson": "fas fa-play-circle",

    },

    "default_icon_parents": "fas fa-chevron-circle-right",

    "default_icon_children": "fas fa-circle",

    "related_modal_active": True,

    "custom_css": "css/admin.css",

}

MERCADO_PAGO_ACCESS_TOKEN = os.getenv(
    'MERCADO_PAGO_ACCESS_TOKEN'
)

print(
    "MP TOKEN:",
    os.getenv("MERCADO_PAGO_ACCESS_TOKEN")
)

RESEND_API_KEY = os.getenv(
    'RESEND_API_KEY'
)

ADMIN_NOTIFICATIONS_EMAIL = os.getenv(
    'ADMIN_NOTIFICATIONS_EMAIL'
)

CSRF_TRUSTED_ORIGINS = [
    "https://neuroeducacion-production.up.railway.app",
]