# Generated by Django 6.0.5 on 2026-05-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('descripcion_corta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tecnologias', models.CharField(blank=True, max_length=255, null=True)),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('link_github', models.URLField(blank=True, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
